### PR TITLE
Adding Guzzle 7 Support

### PR DESCRIPTION
**Pull request by iulyanp**

### CODE REVIEW

**Review by mihaileu — APPROVED** [review]

**Comment by jeromegamez** [comment]
Thanks!

**Comment by jeromegamez** [comment]
FYI, the reason why I didn't release this immediately is that the tests currently fail, and I will probably update the minimum PHP version to ^7.2 at least. 🙈

**Comment by jeromegamez** [comment]
Here it is: [Release 1.2.0](https://github.com/kreait/gcp-metadata-php/releases/tag/1.2.0) 🚀 

Thanks again for the nudge!

**Comment by iulyanp** [comment]
Not a problem. I saw them fail, but I didn't knew why you keep the minimum PHP version at 5. 

Thank you!

**Pull request merged**
